blueprint:
  name: Strażnik wietrzenia pokoju
  description: Powiadamia o zbyt długim wietrzeniu przy dużej różnicy temperatur i opcjonalnie czeka na spadek CO₂.
  domain: automation
  source_url: https://raw.githubusercontent.com/amuamurawski/homeassistant/main/room_airing_watchdog/airing_watchdog.yaml

  input:
    window_contact:
      name: Czujnik okna/drzwi
      description: Wybierz binarny czujnik otwarcia.
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - door
            - window
            - opening

    room_temperature:
      name: Temperatura w pokoju
      description: Czujnik temperatury wewnątrz.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    outdoor_temperature:
      name: Temperatura na zewnątrz
      description: Czujnik temperatury na zewnątrz.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    co2_sensor:
      name: Czujnik CO₂ (opcjonalny)
      description: Pozwala czekać na spadek CO₂ przed alarmem.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide

    notify_target:
      name: Kanał powiadomień
      description: "Przykład: notify.mobile_app_twój_telefon."
      selector:
        text:

    follow_up_entity:
      name: Dodatkowa reakcja
      description: Opcjonalnie wybierz automatyzację lub skrypt do uruchomienia po alarmie.
      default: ""
      selector:
        entity:
          domain:
            - automation
            - script

    temp_diff_threshold:
      name: Próg różnicy temperatur [°C]
      default: 6
      selector:
        number:
          min: 1
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    base_allowed_minutes:
      name: Bazowy dopuszczalny czas [min]
      default: 15
      selector:
        number:
          min: 3
          max: 60
          step: 1
          unit_of_measurement: "min"

    per_degree_penalty:
      name: Skracanie czasu na każdy °C powyżej progu [min/°C]
      default: 2
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: "min/°C"

    min_allowed_minutes:
      name: Minimalny dopuszczalny czas [min]
      default: 5
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: "min"

    co2_target:
      name: Docelowe CO₂ [ppm]
      default: 900
      selector:
        number:
          min: 600
          max: 2000
          step: 50
          unit_of_measurement: "ppm"

    co2_grace_minutes:
      name: Dodatkowy czas przy wysokim CO₂ [min]
      default: 10
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: "min"

    repeat_reminder_minutes:
      name: Powtarzaj przypomnienie co [min]
      description: 0 wyłącza ponowne alerty.
      default: 10
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: "min"

mode: restart
max_exceeded: silent

variables:
  t_room_label: "Pokój"
  t_unknown_room: "nieznany"
  t_temp_diff_label: "Różnica T wew–zew"
  t_window_open_label: "Okno otwarte już"
  t_minutes_suffix: "min"
  t_co2_high_label: "CO₂ nadal wysokie"
  t_notify_title_initial: "Wietrzenie trwa zbyt długo"
  t_notify_title_repeat: "Wietrzenie nadal trwa"
  t_window_closed_title: "Okno zamknięte"
  t_window_closed_message: "Wietrzenie zakończone. Okno zostało zamknięte."
  v_window: !input window_contact
  v_room_t: !input room_temperature
  v_out_t: !input outdoor_temperature
  v_co2: !input co2_sensor
  v_notify: !input notify_target
  v_follow: !input follow_up_entity
  v_thr: !input temp_diff_threshold
  v_base: !input base_allowed_minutes
  v_pen: !input per_degree_penalty
  v_min: !input min_allowed_minutes
  v_co2_target: !input co2_target
  v_co2_grace: !input co2_grace_minutes
  v_repeat: !input repeat_reminder_minutes

triggers:
  - id: opened
    trigger: state
    entity_id: !input window_contact
    to: "on"
    for:
      seconds: 60

  - id: closed
    trigger: state
    entity_id: !input window_contact
    to: "off"

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: opened
        sequence:
          - variables:
              room_t: "{{ states(v_room_t) | float(0) }}"
              out_t: "{{ states(v_out_t) | float(0) }}"
              diff: "{{ (room_t - out_t) | abs }}"
              allowed_min_raw: "{{ v_base - max(0, diff - v_thr) * v_pen }}"
              allowed_min: "{{ [v_min, allowed_min_raw] | max | round(0) }}"
          - if:
              - condition: template
                value_template: "{{ diff >= v_thr }}"
            then:
              - variables:
                  latest_deadline_sec: "{{ (allowed_min + (v_co2_grace if v_co2|length>0 else 0)) * 60 }}"

              - wait_for_trigger:
                  - platform: state
                    entity_id: !input window_contact
                    to: "off"
                  - platform: template
                    value_template: "{{ v_co2|length>0 and (states(v_co2)|float(5000) <= v_co2_target) }}"
                timeout: "{{ latest_deadline_sec | int }}"
                continue_on_timeout: true

              - if:
                  - condition: state
                    entity_id: !input window_contact
                    state: "on"
                then:
                  - variables:
                      msg: >-
                        {{ t_room_label }}: {{ area_name(v_window) or t_unknown_room }}.
                        {{ t_temp_diff_label }}: {{ diff | round(1) }}°C.
                        {{ t_window_open_label }} {{ allowed_min | int }} {{ t_minutes_suffix }}.
                        {% if v_co2|length>0 and states(v_co2)|float(0) > v_co2_target %}
                        {{ t_co2_high_label }}: {{ states(v_co2)|int }} ppm.
                        {%- endif %}
                  - service: "{{ v_notify }}"
                    data:
                      title: "{{ t_notify_title_initial }}"
                      message: "{{ msg }}"
                  - if:
                      - condition: template
                        value_template: "{{ v_follow | length > 0 }}"
                    then:
                      - choose:
                          - conditions:
                              - condition: template
                                value_template: "{{ v_follow.startswith('automation.') }}"
                            sequence:
                              - service: automation.trigger
                                target:
                                  entity_id: "{{ v_follow }}"
                          - conditions:
                              - condition: template
                                value_template: "{{ v_follow.startswith('script.') }}"
                            sequence:
                              - service: script.turn_on
                                target:
                                  entity_id: "{{ v_follow }}"
                  - repeat:
                      while:
                        - condition: state
                          entity_id: !input window_contact
                          state: "on"
                        - condition: template
                          value_template: "{{ v_repeat | int > 0 }}"
                      sequence:
                        - delay:
                            minutes: !input repeat_reminder_minutes
                        - service: "{{ v_notify }}"
                          data:
                            title: "{{ t_notify_title_repeat }}"
                            message: "{{ msg }}"

      - conditions:
          - condition: trigger
            id: closed
        sequence:
          - service: persistent_notification.create
            data:
              title: "{{ t_window_closed_title }}"
              message: "{{ t_window_closed_message }}"
