blueprint:
  name: Room airing watchdog
  description: Alerts when airing takes too long with a large indoor-outdoor temperature difference and can wait for CO₂ to reach a target.
  domain: automation
  source_url: https://raw.githubusercontent.com/amuamurawski/homeassistant/main/room_airing_watchdog/airing_watchdog.yaml

  input:
    window_contact:
      name: Window or door sensor
      description: Select the binary open/close sensor.
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - door
            - window
            - opening

    room_temperature:
      name: Room temperature
      description: Indoor temperature sensor.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    outdoor_temperature:
      name: Outdoor temperature
      description: Outdoor temperature sensor.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    co2_sensor:
      name: CO₂ sensor (optional)
      description: Lets the automation wait for CO₂ to drop.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: carbon_dioxide

    notify_target:
      name: Notification target
      description: "Example: notify.mobile_app_your_phone."
      selector:
        text:

    follow_up_entity:
      name: Follow-up action
      description: Optionally select an automation or script to run after the alert.
      default: ""
      selector:
        entity:
          domain:
            - automation
            - script

    temp_diff_threshold:
      name: Temperature difference threshold [°C]
      default: 6
      selector:
        number:
          min: 1
          max: 30
          step: 0.5
          unit_of_measurement: "°C"

    base_allowed_minutes:
      name: Base allowed time [min]
      default: 15
      selector:
        number:
          min: 3
          max: 60
          step: 1
          unit_of_measurement: "min"

    per_degree_penalty:
      name: Time reduction per °C above threshold [min/°C]
      default: 2
      selector:
        number:
          min: 0
          max: 10
          step: 0.5
          unit_of_measurement: "min/°C"

    min_allowed_minutes:
      name: Minimum allowed time [min]
      default: 5
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: "min"

    co2_target:
      name: Target CO₂ [ppm]
      default: 900
      selector:
        number:
          min: 600
          max: 2000
          step: 50
          unit_of_measurement: "ppm"

    co2_grace_minutes:
      name: Extra time with high CO₂ [min]
      default: 10
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: "min"

    repeat_reminder_minutes:
      name: Repeat reminder every [min]
      description: 0 disables repeat alerts.
      default: 10
      selector:
        number:
          min: 0
          max: 60
          step: 1
          unit_of_measurement: "min"

mode: restart
max_exceeded: silent

variables:
  lang: >
    {% set code = hass.config.language if hass is defined else none %}
    {% set code = code | string | lower if code is not none else 'en' %}
    {{ 'pl' if code.startswith('pl') else 'en' }}
  i18n_raw: >
    {% set strings = {
      'pl': {
        'room': 'Pokój',
        'unknown': 'nieznany',
        'diff': 'Różnica T wew–zew',
        'open': 'Okno otwarte już',
        'minutes': 'min',
        'co2_high': 'CO₂ nadal wysokie',
        'alert': 'Wietrzenie trwa zbyt długo',
        'still': 'Wietrzenie nadal trwa',
        'closed_title': 'Okno zamknięte',
        'closed_msg': 'Wietrzenie zakończone. Okno zostało zamknięte.'
      },
      'en': {
        'room': 'Room',
        'unknown': 'unknown',
        'diff': 'Indoor-outdoor temp diff',
        'open': 'Window open for',
        'minutes': 'min',
        'co2_high': 'CO₂ still high',
        'alert': 'Airing taking too long',
        'still': 'Airing still in progress',
        'closed_title': 'Window closed',
        'closed_msg': 'Airing finished. The window has been closed.'
      }
    } %}
    {{ strings[lang] | tojson }}
  t: "{{ i18n_raw | from_json }}"
  v_window: !input window_contact
  v_room_t: !input room_temperature
  v_out_t: !input outdoor_temperature
  v_co2: !input co2_sensor
  v_notify: !input notify_target
  v_follow: !input follow_up_entity
  v_thr: !input temp_diff_threshold
  v_base: !input base_allowed_minutes
  v_pen: !input per_degree_penalty
  v_min: !input min_allowed_minutes
  v_co2_target: !input co2_target
  v_co2_grace: !input co2_grace_minutes
  v_repeat: !input repeat_reminder_minutes

triggers:
  - id: opened
    trigger: state
    entity_id: !input window_contact
    to: "on"
    for:
      seconds: 60

  - id: closed
    trigger: state
    entity_id: !input window_contact
    to: "off"

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: opened
        sequence:
          - variables:
              room_t: "{{ states(v_room_t) | float(0) }}"
              out_t: "{{ states(v_out_t) | float(0) }}"
              diff: "{{ (room_t - out_t) | abs }}"
              allowed_min_raw: "{{ v_base - max(0, diff - v_thr) * v_pen }}"
              allowed_min: "{{ [v_min, allowed_min_raw] | max | round(0) }}"
          - if:
              - condition: template
                value_template: "{{ diff >= v_thr }}"
            then:
              - variables:
                  latest_deadline_sec: "{{ (allowed_min + (v_co2_grace if v_co2|length>0 else 0)) * 60 }}"

              - wait_for_trigger:
                  - platform: state
                    entity_id: !input window_contact
                    to: "off"
                  - platform: template
                    value_template: "{{ v_co2|length>0 and (states(v_co2)|float(5000) <= v_co2_target) }}"
                timeout: "{{ latest_deadline_sec | int }}"
                continue_on_timeout: true

              - if:
                  - condition: state
                    entity_id: !input window_contact
                    state: "on"
                then:
                  - variables:
                      msg: >-
                        {{ t.room }}: {{ area_name(v_window) or t.unknown }}.
                        {{ t.diff }}: {{ diff | round(1) }}°C.
                        {{ t.open }} {{ allowed_min | int }} {{ t.minutes }}.
                        {% if v_co2|length>0 and states(v_co2)|float(0) > v_co2_target %}
                        {{ t.co2_high }}: {{ states(v_co2)|int }} ppm.
                        {%- endif %}
                  - service: "{{ v_notify }}"
                    data:
                      title: "{{ t.alert }}"
                      message: "{{ msg }}"
                  - if:
                      - condition: template
                        value_template: "{{ v_follow | length > 0 }}"
                    then:
                      - choose:
                          - conditions:
                              - condition: template
                                value_template: "{{ v_follow.startswith('automation.') }}"
                            sequence:
                              - service: automation.trigger
                                target:
                                  entity_id: "{{ v_follow }}"
                          - conditions:
                              - condition: template
                                value_template: "{{ v_follow.startswith('script.') }}"
                            sequence:
                              - service: script.turn_on
                                target:
                                  entity_id: "{{ v_follow }}"
                  - repeat:
                      while:
                        - condition: state
                          entity_id: !input window_contact
                          state: "on"
                        - condition: template
                          value_template: "{{ v_repeat | int > 0 }}"
                      sequence:
                        - delay:
                            minutes: !input repeat_reminder_minutes
                        - service: "{{ v_notify }}"
                          data:
                            title: "{{ t.still }}"
                            message: "{{ msg }}"

      - conditions:
          - condition: trigger
            id: closed
        sequence:
          - service: persistent_notification.create
            data:
              title: "{{ t.closed_title }}"
              message: "{{ t.closed_msg }}"
